'use strict'; // code generated by pbf v3.2.1

// Dot ========================================

var Dot = exports.Dot = {};

Dot.read = function (pbf, end) {
    return pbf.readFields(Dot._readField, {raceCode: 0, latitude: 0, longitude: 0}, end);
};
Dot._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.raceCode = pbf.readVarint(true);
    else if (tag === 2) obj.latitude = pbf.readFloat();
    else if (tag === 3) obj.longitude = pbf.readFloat();
};
Dot.write = function (obj, pbf) {
    if (obj.raceCode) pbf.writeVarintField(1, obj.raceCode);
    if (obj.latitude) pbf.writeFloatField(2, obj.latitude);
    if (obj.longitude) pbf.writeFloatField(3, obj.longitude);
};

// Dots ========================================

var Dots = exports.Dots = {};

Dots.read = function (pbf, end) {
    return pbf.readFields(Dots._readField, {dots: []}, end);
};
Dots._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.dots.push(Dot.read(pbf, pbf.readVarint() + pbf.pos));
};
Dots.write = function (obj, pbf) {
    if (obj.dots) for (var i = 0; i < obj.dots.length; i++) pbf.writeMessage(1, Dot.write, obj.dots[i]);
};
